//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once


namespace winrt::J_Encrypter::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct MainWindowT : public ::winrt::J_Encrypter::implementation::MainWindow_base<D,
        ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector,
        I...>
    {
        using base_type = typename MainWindowT::base_type;
        using base_type::base_type;
        using class_type = typename MainWindowT::class_type;

        void InitializeComponent();
        void Connect(int32_t connectionId, IInspectable const& target);
        ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Microsoft::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Microsoft::UI::Xaml::Controls::TextBox inpTxt()
        {
            return _inpTxt;
        }
        void inpTxt(::winrt::Microsoft::UI::Xaml::Controls::TextBox value)
        {
            _inpTxt = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBox outTxt()
        {
            return _outTxt;
        }
        void outTxt(::winrt::Microsoft::UI::Xaml::Controls::TextBox value)
        {
            _outTxt = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBox seedTxt()
        {
            return _seedTxt;
        }
        void seedTxt(::winrt::Microsoft::UI::Xaml::Controls::TextBox value)
        {
            _seedTxt = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBox offTxt()
        {
            return _offTxt;
        }
        void offTxt(::winrt::Microsoft::UI::Xaml::Controls::TextBox value)
        {
            _offTxt = value;
        }
        
    protected:
        bool _contentLoaded{false};

    private:
        struct MainWindow_obj1_Bindings;

        ::winrt::Microsoft::UI::Xaml::Controls::TextBox _inpTxt{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBox _outTxt{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBox _seedTxt{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBox _offTxt{nullptr};
    };
}

