// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210806.1

void* winrt_make_J_Encrypter_MainWindow()
{
    return winrt::detach_abi(winrt::make<winrt::J_Encrypter::factory_implementation::MainWindow>());
}
WINRT_EXPORT namespace winrt::J_Encrypter
{
    MainWindow::MainWindow() :
        MainWindow(make<J_Encrypter::implementation::MainWindow>())
    {
    }
}
