// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210806.1

void* winrt_make_J_Encrypter_XamlMetaDataProvider()
{
    return winrt::detach_abi(winrt::make<winrt::J_Encrypter::factory_implementation::XamlMetaDataProvider>());
}
WINRT_EXPORT namespace winrt::J_Encrypter
{
    XamlMetaDataProvider::XamlMetaDataProvider() :
        XamlMetaDataProvider(make<J_Encrypter::implementation::XamlMetaDataProvider>())
    {
    }
}
