// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210806.1

#pragma once
#ifndef WINRT_J_Encrypter_0_H
#define WINRT_J_Encrypter_0_H
WINRT_EXPORT namespace winrt::Microsoft::UI::Xaml::Markup
{
    struct IXamlMetadataProvider;
}
WINRT_EXPORT namespace winrt::J_Encrypter
{
    struct IMainWindow;
    struct MainWindow;
    struct XamlMetaDataProvider;
}
namespace winrt::impl
{
    template <> struct category<winrt::J_Encrypter::IMainWindow>{ using type = interface_category; };
    template <> struct category<winrt::J_Encrypter::MainWindow>{ using type = class_category; };
    template <> struct category<winrt::J_Encrypter::XamlMetaDataProvider>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::J_Encrypter::MainWindow> = L"J_Encrypter.MainWindow";
    template <> inline constexpr auto& name_v<winrt::J_Encrypter::XamlMetaDataProvider> = L"J_Encrypter.XamlMetaDataProvider";
    template <> inline constexpr auto& name_v<winrt::J_Encrypter::IMainWindow> = L"J_Encrypter.IMainWindow";
    template <> inline constexpr guid guid_v<winrt::J_Encrypter::IMainWindow>{ 0x71941166,0x9449,0x5D62,{ 0xB1,0x2D,0x9C,0xDA,0xB4,0x2B,0x5D,0xD3 } }; // 71941166-9449-5D62-B12D-9CDAB42B5DD3
    template <> struct default_interface<winrt::J_Encrypter::MainWindow>{ using type = winrt::J_Encrypter::IMainWindow; };
    template <> struct default_interface<winrt::J_Encrypter::XamlMetaDataProvider>{ using type = winrt::Microsoft::UI::Xaml::Markup::IXamlMetadataProvider; };
    template <> struct abi<winrt::J_Encrypter::IMainWindow>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall get_MyProperty(int32_t*) noexcept = 0;
            virtual int32_t __stdcall put_MyProperty(int32_t) noexcept = 0;
        };
    };
    template <typename D>
    struct consume_J_Encrypter_IMainWindow
    {
        [[nodiscard]] WINRT_IMPL_AUTO(int32_t) MyProperty() const;
        WINRT_IMPL_AUTO(void) MyProperty(int32_t value) const;
    };
    template <> struct consume<winrt::J_Encrypter::IMainWindow>
    {
        template <typename D> using type = consume_J_Encrypter_IMainWindow<D>;
    };
}
#endif
