// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210806.1

void* winrt_make_CustomEncryption_MainWindow()
{
    return winrt::detach_abi(winrt::make<winrt::CustomEncryption::factory_implementation::MainWindow>());
}
WINRT_EXPORT namespace winrt::CustomEncryption
{
    MainWindow::MainWindow() :
        MainWindow(make<CustomEncryption::implementation::MainWindow>())
    {
    }
}
